# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='(?P<category_name_slug>[\\w\\-]+)'),
        ),
    ]
